# Generated by Django 4.0.5 on 2022-07-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('planId', models.IntegerField()),
                ('selectedAmount', models.IntegerField()),
                ('selectedTenure', models.IntegerField()),
                ('startDate', models.DateField()),
                ('depositedAmount', models.IntegerField()),
                ('benefitPercentage', models.FloatField()),
                ('benifitType', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('planId', models.AutoField(primary_key=True, serialize=False)),
                ('planName', models.CharField(default='', max_length=64)),
                ('amountOptions', models.CharField(max_length=64)),
                ('tenureOptions', models.IntegerField()),
                ('benefitPercentage', models.FloatField()),
                ('benefitType', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promotionId', models.AutoField(primary_key=True, serialize=False)),
                ('promotionType', models.CharField(default='', max_length=64)),
                ('promotionData', models.CharField(default='', max_length=64)),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tortoise.plans')),
            ],
        ),
    ]
