# Generated by Django 4.0.5 on 2022-07-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='planId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tortoise.plans'),
        ),
    ]
